CREATE TABLE `partner_companies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyName` varchar(255) NOT NULL,
	`businessType` enum('catering','photography_video','chef_services','decoration','sound_lighting','transportation','security','cleaning','other') NOT NULL,
	`contactPerson` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`address` text,
	`city` varchar(100),
	`county` varchar(100),
	`postcode` varchar(20),
	`servicesOffered` text,
	`description` text,
	`website` varchar(500),
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `partner_companies_id` PRIMARY KEY(`id`)
);
